#+ enumerate: 
#+ - groupattribute:
#+    - http://example.org/children
#+    - http://example.org/adolescents
#+    - http://example.org/high
#+    - http://example.org/low

PREFIX : <http://example.org/>
CONSTRUCT {
  ?group ?attribute ?_groupattribute_iri .
}
WHERE {
  ?claim :socialGroup ?group .     
  ?group ?attribute ?_groupattribute_iri .
} 
