#+ enumerate: 
#+ - socialgroup 
#+    - http://example.org/children
#+    - http://example.org/adolescents

PREFIX : <http://example.org/>
CONSTRUCT {
  ?group :ageCategory ?_age_iri .
  ?group ?pred ?obj .
}
WHERE {
  ?group :ageCategory ?_age_iri .     
  ?group ?pred ?obj .
} 
